### ISSUE TITLE
Package for Linux aarch64

### ISSUE THREAD

**Issue by axiopaladin** [JabRef/jabref#10842]
### Can Linux aarch64 be added to the list for standard build targets?
I want to run JabRef on my ARM Linux devices. Unfortunately, the only JabRef builds released for Linux right now are for x86-based architectures.

I'll work on trying to compile a binary for my own use, but I figure it would be a nice addition to the CI pipeline too.

**Comment by Siedlerchr** [comment]
@axiopaladin We would offer an arm-based image; however, GitHub currently doesn't provide an ARM based hosted runner ,only for self-hosting. 

ARM based runners are only in closed beta right now https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/ 


**For self compiling:** 
You need to clone JabRef and init the submodules.
If you want to  compile it yourself, you basically need to have jdk21 + gradle
Simply running  ` ./gradlew jpackage` will be sufficient to build the executables.

See also:
https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/

**Comment by Siedlerchr** [comment]
Ah seems like they have not yet? released the aarch64 binaries for Linux in jfx 21.0.2, in 21.0.1. they are present
e.g. 

You could change that version in the build.gradle file 
https://repo.maven.apache.org/maven2/org/openjfx/javafx-fxml/21.0.2/

When cloning the repo you need to include the submodules for the csl styles and abbrevs
`git clone --recurse-submodules https://github.com/JabRef/jabref.git`

**Comment by axiopaladin** [comment]
@Siedlerchr thanks for the tips. I apologize for my last post being a little unfocused, I'm glad you were able to decipher it! I was unfamiliar with gradle so I've been learning as I go here; I think I'm finally barely starting to understand how `build.gradle` works.

I was able to get something built! I had to do a few hacks along the way, though:

1. `apt update; apt install fakeroot` inside this Ubuntu-based `arm64v8/gradle:jdk21` docker image
2. Add the following changes to `build.gradle`:
```gradle
javafx { // <-- line 103 of build.gradle
    version = "22-ea+27" // changed to most recent version with aarch64 binaries released
    modules = [ 'javafx.controls', 'javafx.fxml', 'javafx.web', 'javafx.swing' ]
}
```

```gradle
            installerOptions = [
                    '--verbose',
                    '--type', 'deb', // <-- add this here, at line 660
                    '--vendor', 'JabRef',
                    '--app-version', "${project.version}",
                    //'--temp', "$buildDir/installer",
                    '--resource-dir', "${projectDir}/buildres/linux",
                    '--linux-menu-group', 'Office;',
                    // '--linux-rpm-license-type', 'MIT',
                    // '--license-file', "${projectDir}/LICENSE.md",
                    '--description', 'JabRef is an open source bibliography reference manager. The native file format used by>
                    '--linux-shortcut',
                    '--file-associations', "${projectDir}/buildres/linux/bibtexAssociations.properties"
            ]
```

After all that, a `./gradlew jpackage` ended in a successful build!

However, I'm not sure how to export a useful binary from this. When I try to use dpkg to install the `.deb` that is produced (in `build/distribution/`), inside the docker container, it complains about dependencies, so clearly that isn't self-contained. If I try to run the executable binary `build/distribution/JabRef/bin/JabRef` inside the docker container, it complains about not having a display (which is reasonable), and if I try it outside the container it throws this error:

```
Error occurred during initialization of VM
Unable to load jimage library: jabref/build/distribution/JabRef/lib/runtime/lib/libjimage.so
```

I apologize if this is a foolish question, as I am not even a novice in gradle-fu, but how difficult would it be to convince jpackage to spit out a static/portable binary for the project as a whole? (Or perhaps the more appropriate solution would be to build a flatpak or similar containerized solution instead?)

In the [releases](https://github.com/JabRef/jabref/releases) for this project, I suppose the closest equivalent to what I'm looking for would be the `JabRef-X.xx-portable_linux.tar.gz` option (but for aarch64 instead of x86_64, of course). I thought that was what `build/distribution/JabRef` contained, but apparently not? I can run the official release just fine (on an x86 machine) but my own compiled binary doesn't work at all on my aarch64 machine.

**Comment by Siedlerchr** [comment]
Hi, your approach looks already good, for the portable it would be sufficient to call ` ./gradlew jlinkzip`
The application should also be self-contained with the java runtime.  
can you integrate a  step in the docker file to print out the java version? Should be  `java -version`and verify it's 21.0.1  or 21.0.2 (important)

**Comment by axiopaladin** [comment]
```bash
# java -version
openjdk version "21.0.2" 2024-01-16 LTS
OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode, sharing)
```

I've rebuilt with `./gradlew jlinkzip` and I've gotten (what I assume is) the output at `build/image.zip`. However, it throws that same `Error occurred during initialization of VM` `Unable to load jimage library` message when I tried unzipping it and running the `image/bin/JabRef` binary. 

My primary ARM system (that I've been using to test these) is running an Alpine-based distribution, perhaps some glibc dependency has leaked into the JabRef output and *that* is the real issue? I don't have any other ARM systems handy right now (...maybe this is an excuse to order another raspberry pi 🤔) so I'll just upload my image.zip [here](https://encl.io/t/cKbGXXpoTec#qeGqRHM_ZM4BUWh7qg32EA). If someone else has a non-Alpine aarch64 machine and feels like testing it out, that would be helpful :) Otherwise I'll put together a live USB or something to test with eventually.

**Comment by axiopaladin** [comment]
I've tried building for Alpine with the following (much more elegant) `docker-compose.yml`, and it throws a new and different error instead of building successfully, so that's interesting!

```yml
version: "3.9"

services:
  alpine:
    image: alpine:latest
    network_mode: host
    restart: on-failure
    tty: true
    volumes:
      - ./working:/working:rw
    command: >
      sh -c 'apk update &&
             apk add --no-interactive git openjdk21 &&
             cd /working &&
             git clone --recurse-submodules https://github.com/JabRef/jabref.git 2> /dev/null ||
             (cd jabref ; git pull) &&
             java -version &&
             cd /working/jabref &&
             sed -i "s/21.0.2/22-ea+27/g" build.gradle &&
             ./gradlew jlinkzip ;
             ash'
```

I've automated all the important bits in this one, so just `cd` into the same folder and `docker-compose run -i alpine` and it should go through the built-in script to grab everything necessary and build. (At the end, I have it leave you at a command prompt in case you want to do more before shutting down the container.)

Gradle throws the following strange error when I run it on my aarch64 machine:

```md
> Task :processResources FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/working/jabref/build.gradle' line: 285

* What went wrong:
Execution failed for task ':processResources'.
> Could not list contents of directory '/working/jabref/src/main/resources'.
```

I've checked the file permissions of that `src/main/resources` folder and I can't figure out why it would be inaccessible to java. I'll have to give it a try on an x86_64 machine later and see if it can build successfully there...

**Comment by Siedlerchr** [comment]
Hm, what I found online is only rare, there someone was using alpine as docker base image and had the same image...
Apparently, adding `libc6-compat`  or something like gcompat helped. But I have no idea.

You. need `binutils` for jlink as well

**Comment by Siedlerchr** [comment]
Hm, what I found online is only rare, there someone was using alpine as docker base image and had the same image...
Apparently, adding `libc6-compat` helped. But I have no idea.

And `/lib/runtime/bin/JabRef` does not work either, I guess ?

**Comment by axiopaladin** [comment]
- I had gcompat and libc6-compat on my base system already, so unfortunately it seems they can't solve the issue :(
 - I've just now tried adding binutils to the Alpine-based docker build and it does not get me past that "can't access `src/main/resources`" problem, so I don't think it's that.
 - Unfortunately the alpine-based Gradle docker images are only for x86_64, none for ARM.

**Comment by axiopaladin** [comment]
Alright, I've tried building with the exact same script on both aarch64 and x86_64. Here's my latest and greatest `docker-compose.yml` file:

```yml
version: "3.9"

services:
  alpine:
    image: alpine:latest
    network_mode: host
    restart: on-failure
    tty: true
    volumes:
      - ./working:/working:rw
    command: >
      sh -c 'apk update &&
             apk add --no-interactive binutils dpkg fakeroot git openjdk21 rpm &&
             cd /working &&
             git clone --recurse-submodules https://github.com/JabRef/jabref.git ||
             (cd jabref ; git pull) &&
             java -version &&
             cd /working/jabref &&
             sed -i "s/21.0.2/22-ea+27/g" build.gradle &&
             ./gradlew jlinkzip ;
             ash'
```

It automatically installs all the necessary prerequisites, pulls the JabRef sources from GitHub, and runs the build process. (For @koppor -- put the `docker-compose.yml` in an empty directory and `docker-compose run -i alpine` from there to start it up and attach your terminal to it.)

On my x86_64 machine, it builds just fine; on my ARM machine, it fails partway through with the following error:

```
{todo: paste error message here}
```

---

That said, this exercise wasn't completely fruitless. One interesting thing that I noticed was that there *does* seem to be a difference between the images built on Ubuntu-based toolchains and those built on Alpine-based toolchains. Running `ldd {unzipped image.zip}/bin/java`, for example, shows that the Alpine-created binary relies on dynamic links specifically to Alpine's musl libraries:

```
$ ldd bin/java
        /lib/ld-musl-x86_64.so.1 (0x7f72664f0000)
        libjli.so => bin/../lib/libjli.so (0x7f72664db000)
        libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f72664f0000)
        libz.so.1 => /lib/libz.so.1 (0x7f72664c1000)
```

I think this explains why the aarch64 image I was able to build with the (Ubuntu-based) `arm64v8/gradle:jdk21` container wouldn't run on my Alpine-based main system.
