### ISSUE TITLE
Create study-lock.yml

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#12640]
Drivers: 

- `study.yml` should be unmodified by JabRef
- The SLR should be reproducible. That means, researchers should be able to execute the queries without JabRef (e.g., by a Python client or a web browser)

Introduce `study-lock.yml` (similar to `package-lock.json`), where the really sent queries are contained. The -lock is a "superset" of the .yml file.

`study.yml`:

```
queries:
- query: JabRef AND Java
  - ACM Portal: "def"
  - IEEExplore: "abc"
```

`study-lock.yml`:

```yaml
queries:
- query: JabRef AND Java
  - ACM Portal: "def"
  - IEEExplore: "abc"
  - GVK: "abc"
```
