### ISSUE TITLE
Alternative serialization format as core data file (e.g. YAML in addition to BibTeX)

### ISSUE THREAD

**Issue by mjfs** [JabRef/jabref#6974]
Alternative serialization format support (e.g. YAML in addition to BibTeX)

Probably many use cases where `JabRef`'s data file is used include `Pandoc`. Although it is common to use `BibTeX` as input into `pandoc-citeproc`, `YAML` serialized `BibTeX` (citeproc YAML) is also an option. When using `Pandoc`'s flavour of `markdown`, `YAML` is also the format of the metadata block.

It would be fantastic if `JabRef` could read and write `YAML` serialized `BibTeX`. In addition YAML is also less cumbersome to deal with when one needs to do some manual editing of the data file.

Furthermore by supporting `YAML` there is also a possibility of directly copy pasting selected references from `JabRef` data file into the `markdown`'s metadata segment (in addition to the possibility of using external references file exclusively).

Bellow is an example of currently the only `JabRef`'s option and under it what would be great to see `JabRef` also supporting.

Original in `BibTeX`:

```bib
% Encoding: UTF-8
@Misc{id_doc,
    author = {{John Doe}},
    title  = {{Doc Title}},
    date   = {2020-10-03},
    url    = {http://www.example.com}
}
```

Converted to YAML that is recognized by `Pandoc` / `pandoc-citeproc`:

```yaml
---
references:
- id: id_doc
  type: no-type
  author:
  - literal: John Doe
  title: Doc Title
  issued: [[2020,10,3]]
  URL: http://www.example.com
...
```
